# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy3'

install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi



jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/webcolors-stubs
        provider: pypi
        user: "DomDF"
        password:
          secure: mSdDudqXJTAJGTeyVlhuuQbEoX5SU85PVc3t0O4HKgufvXZ7AagGM67MM7xSxcvD9VXFGqZhe3bh9waZumPM1I63rLTIF7g7/UjCluUWY3uOIUnAVQofcg9KsRP0ecaS4DlQQsYyIL2Dos5SlOsUFluFWZl7Z+IfR/UNQNijcn6Wx6E03TvUSr6hK0L7N0nRNuas3mC1XI5SHxFmi/B4lFsefKNi/kTYSjqUF+zUaBX3Ed3SRwjkMzFgSgHVNs1Ddp9s2iqRIRZvyXFd/HSXdCovvxzS9yDPInKMX6bZoi0z+PorIwIwvO5tyrdSCqd8Q9DS/EiPKcgXhrMHkcRS35r1HqBQldtUfPJMIcuOek0HHZHBWGh5c+zMwTNG63i3znIShBiXNPUEfJj4KDVPKnQBVTIJcKTUlnmabInKsU4RlTPbjRPDhs5oXVRtrxlWiPbtAIJsNckuqq9/L7rHbCIF7UB6E3BlqDPKEUeni6un4Z4XW/BRv4F2knSTww+Q/iZCZeXqISe0A0sZ5BVm+uwj7yOli7sSrGL7rG1mATNkPD4YNdVOG2efVOm2sBlgaV2vU2jBIgQ2Y99v/1tX1R0lNuxPS814wuEjkpY/20fauAC8LaLpY8adv70McE53n7fVPDjGkvEy5d5H3o4Au1s7aeLxuQPESgvj4HY5scI=
        distributions: "sdist bdist_wheel"
        skip_existing: true
